import Head from "next/head";
import axios from "axios";
import { Page, Hero, About } from "../components";

export default function Home({ cover, gallery, tags, about, email }) {
  return (
    <Page cover={cover}>
      <Head>
        <title>Introspective Images</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <About about={about} email={email} />
    </Page>
  );
}

export const getServerSideProps = async () => {
  try {
    const imgData = await axios.get(`/api/admin/images`);
    const infoData = await axios.get(`/api/admin/info`);
    return {
      props: {
        cover: imgData.data.data.cover,
        gallery: imgData.data.data.gallery,
        tags: imgData.data.data.tags,
        about: infoData.data.data.about,
        email: infoData.data.data.email,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        cover: null,
        gallery: null,
        tags: null,
        about: null,
        email: null,
      },
    };
  }
};
