import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Hero from "../components/Hero";
import Nav from "../components/Nav";
import About from "../components/About";
import Gallery from "../components/Gallery/Gallery";
import axios from "axios";

export default function Home({ cover, gallery }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Introspective Images</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Hero cover={cover} />
      <About />
      <Gallery imgs={gallery} />
    </div>
  );
}

export const getStaticProps = async () => {
  const { data } = await axios.get("http://localhost:3000/api/admin");
  return {
    props: {
      cover: data.data.cover,
      gallery: data.data.gallery,
    },
  };
};
